name: Test
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Golang Environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Test
        run: go test -race -shuffle=on -v ./...
